title: Estudo sobre os usuários de internet brasileiros
description: Projeto final da disciplina de Metodologia, ministrada pela prof. Thaís Gaudêncio do Rego, do curso de Engenharia de Computação da UFPB.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman